# This role is necessary to create leader lock configmap and lease for cluster-policy-controller
# TODO: configmaps should be removed once cluster-policy-controller is moved to exclusively lease lock
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-kube-controller-manager
  name: system:openshift:leader-election-lock-cluster-policy-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - create
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  resourceNames:
  - cluster-policy-controller-lock
  verbs:
  - get
  - create
  - update
