# This role is necessary to create leader lock for cluster-policy-controller
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-kube-controller-manager
  name: system:openshift:leader-election-lock-cluster-policy-controller
roleRef:
  kind: Role
  name: system:openshift:leader-election-lock-cluster-policy-controller
subjects:
- kind: User
  name: system:kube-controller-manager
